### ISSUE TITLE
sanpy undetected after installing 

### ISSUE THREAD

**Issue by amirprog31** [santiment/sanpy#148]
`PS K:\python bot> pip show sanpy
Name: sanpy
Version: 0.10.0
Summary: Package for Santiment API access with python
Home-page: https://github.com/santiment/sanpy
Author: Santiment
Author-email: admin@santiment.net
License: MIT
Location: f:\program file\python\lib\site-packages
Requires: iso8601, pandas, requests, setuptools
Required-by:`
`PS K:\python bot> pip show pandas 
Name: pandas
Version: 1.4.2
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: f:\program file\python\lib\site-packages
Requires: numpy, python-dateutil, pytz
Required-by: sanpy`
this is pandas and sanpy version in vscode but after test the lib and run program I see this error .
this is my program :
`import san
san.get(
    "daily_active_addresses/santiment",
    from_date="2018-06-01",
    to_date="2018-06-05",
    interval="1d"
)

san.get(
    "prices/santiment",
    from_date="2018-06-01",
    to_date="2018-06-05",
    interval="1d"
)`
and this is my error 👍 
`Exception has occurred: ModuleNotFoundError
No module named 'san'
  File "K:\python bot\sanpy.py", line 1, in <module>
    import san`
also I see this in terminal 👍:
`Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\amir\.vscode\extensions\ms-python.python-2022.8.0\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>   
    cli.main()
  File "c:\Users\amir\.vscode\extensions\ms-python.python-2022.8.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, 
in main
in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "k:\python bot\sanpy.py", line 1, in <module>
    import san
ModuleNotFoundError: No module named 'san'`
🥇 also see this in problem section of vscode :

[{
	"resource": "/k:/python bot/sanpy.py",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 4,
	"message": "Import \"san\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 1,
	"startColumn": 8,
	"endLineNumber": 1,
	"endColumn": 11
}]
### - [ ] how can i solve this and use the lib ?

**Comment by IvanIvanoff** [comment]
This is not a problem with sanpy but with your local setup. I am afraid we cannot help much here.
If you still have problems, you can join our Discord and find help there: https://santiment.net/discord
